# Generated by Django 6.0.2 on 2026-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
