# Generated by Django 6.0.2 on 2026-03-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report_flag_reason_report_is_flagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Bootstrap icon name (e.g., bi-laptop)', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
