# Generated by Django 6.0.2 on 2026-03-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_confirmed',
        ),
    ]
