# Generated by Django 6.0.2 on 2026-03-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_match_created_at_match_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('confirmed', 'Confirmed'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
