# Generated by Django 6.0.2 on 2026-03-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='question_1',
            field=models.CharField(blank=True, default='Can you describe a unique feature of this item?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='question_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='requires_photo_proof',
            field=models.BooleanField(default=False),
        ),
    ]
