# Generated by Django 6.0.2 on 2026-03-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_report_question_1_report_question_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='answer_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='answer_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='claim_proofs/'),
        ),
    ]
