# Generated by Django 6.0.2 on 2026-04-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_transaction_created_at_transaction_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('confirmed', 'Identity Verified'), ('paid', 'Reward Secured in Escrow'), ('returned', 'Item Handover Complete'), ('rejected', 'Match Rejected')], default='pending', max_length=20),
        ),
    ]
