# Generated by Django 6.0.2 on 2026-04-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
