# Generated by Django 6.0.2 on 2026-04-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_admin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='static_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
