# Generated by Django 6.0.2 on 2026-04-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_item_static_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='static_image_path',
        ),
    ]
